/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utils_JNIWrappers_TextureBlender */

#ifndef _Included_Utils_JNIWrappers_TextureBlender
#define _Included_Utils_JNIWrappers_TextureBlender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utils_JNIWrappers_TextureBlender
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Utils_JNIWrappers_TextureBlender_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
