/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utils_JNIWrappers_TextureBlender */

#ifndef _Included_Utils_JNIWrappers_TextureBlender
#define _Included_Utils_JNIWrappers_TextureBlender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utils_JNIWrappers_TextureBlender
 * Method:    drawOverTiled
 * Signature: ([BII[BIIDDDD)V
 */
JNIEXPORT void JNICALL Java_Utils_JNIWrappers_TextureBlender_drawOverTiled
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Utils_JNIWrappers_TextureBlender
 * Method:    drawOver
 * Signature: ([III[BII[BDDDDZI)V
 */
JNIEXPORT void JNICALL Java_Utils_JNIWrappers_TextureBlender_drawOver
  (JNIEnv *, jclass, jintArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jdouble, jdouble, jdouble, jdouble, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
